//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiplomBuildingShopEntities : DbContext
    {
        public DiplomBuildingShopEntities()
            : base("name=DiplomBuildingShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<Категория_товаров> Категория_товаров { get; set; }
        public virtual DbSet<Клиент> Клиент { get; set; }
        public virtual DbSet<Сотрудник> Сотрудник { get; set; }
        public virtual DbSet<Список_товаров> Список_товаров { get; set; }
        public virtual DbSet<Товар> Товар { get; set; }
    }
}
