//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ()
        {
            this.Список_товаров = new HashSet<Список_товаров>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_клиента { get; set; }
        public Nullable<int> id_сотрудника { get; set; }
        public bool Готовность { get; set; }
        public System.DateTime Дата { get; set; }
        public Nullable<decimal> Сумма { get; set; }
    
        public virtual Клиент Клиент { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Список_товаров> Список_товаров { get; set; }
    }
}
