//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Список_товаров
    {
        public int id { get; set; }
        public Nullable<int> id_товара { get; set; }
        public Nullable<int> id_заказа { get; set; }
        public Nullable<int> Кол_во { get; set; }
        public Nullable<decimal> Цена { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
