//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товар()
        {
            this.Список_товаров = new HashSet<Список_товаров>();
        }
    
        public int id { get; set; }
        public string Наименование { get; set; }
        public string Описание { get; set; }
        public Nullable<int> id_категории { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public string Страна_производитель { get; set; }
        public string Производитель { get; set; }
        public int Количество { get; set; }
    
        public virtual Категория_товаров Категория_товаров { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Список_товаров> Список_товаров { get; set; }
    }
}
